# Generated by Django 4.2.1 on 2024-11-23 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employer',
            options={'verbose_name': 'Employer', 'verbose_name_plural': 'Employers'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
    ]
