# Generated by Django 4.2.1 on 2024-11-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_auth', '0002_alter_employer_options_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('employer', 'Employer')], max_length=10, null=True),
        ),
    ]
