# Generated by Django 4.2.1 on 2024-11-24 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_auth', '0004_alter_user_options_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='Employer',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
